# Generated by Django 4.0.6 on 2022-08-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renovation', models.BooleanField(default=False)),
                ('coloring', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
